print("Hola Mundo")
print("Mi nombre es Eric")
print("Me gusta programar")
print("Me gusta python")
print("Me gusta cocinar")
print("Me gusta ver anime")
print("Me gusta escuchar musica")
print("Me gusta viajar")
